apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - django-deployment.yaml
  - django-service.yaml
  - configmap.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - redis-deployment.yaml
  - redis-service.yaml
